spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
  datasource:
    #url: jdbc:h2:mem:cbodb
    #This will crete database files in the RI root /data folder
    url: jdbc:h2:file:./data/cbodb
    username: sa
    password:
    driverClassName: org.h2.Driver

swagger:
  title: SDOH Exchange CBO App API
  contact:
    name: Gravity Project
    url: https://www.hl7.org/gravity/

server:
  port: 8084