ehr:
  fhir-server-uri: https://api.logicahealth.org/GravitySandboxNew/data
  open-fhir-server-uri: https://api.logicahealth.org/GravitySandboxNew/open
  identifier-system: http://hl7.org/gravity/sdoh-ri

spring:
  security:
    oauth2:
      client:
        registration:
          ehr-client:
            client-id: 74d2dd60-05c8-4b15-b500-06fd9f022157
            client-secret: ANJV4C6tZRUkXlKvCcnrKq7UoqVq8q18y0gQ_hZ55jTPiCuzV9eWGJVdOkb0cAiL8bu87q5L_lwEPOn4AbmRUg0
            client-name: Gravity-SDOH-Exchange-EHR-App-LOCAL
            provider: ehr-provider
            redirect-uri: "http://localhost:8080/login/oauth2/code/ehr-client"
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            # scope 'launch/patient' for a standalone launch if needed.
            scope: 'launch,launch/patient,fhirUser,user/*.read,openid,patient/*.*'
        provider:
          ehr-provider:
            token-uri: https://auth.logicahealth.org/token
            # We need to explicitly set the 'aud' query param to enable standalone launch.
            authorization-uri: https://auth.logicahealth.org/authorize?aud=${ehr.fhir-server-uri}
            user-info-uri: https://auth.logicahealth.org/userinfo
            jwk-set-uri: https://auth.logicahealth.org/jwk
            userNameAttribute: sub

swagger:
  title: SDOH Exchange EHR App API
  contact:
    name: Gravity Project
    url: https://www.hl7.org/gravity/
scheduling:
  task-polling-delay-millis: 30000