ehr:
  fhir-server-uri: https://api.logicahealth.org/GravityMaxEHR/data
  open-fhir-server-uri: https://api.logicahealth.org/GravityMaxEHR/open

spring:
  security:
    oauth2:
      client:
        registration:
          ehr-client:
            client-id: bd676c67-2735-470a-bf6f-c55456f5bd95
            client-secret: IjWyE2D6QjaGNItKs0JTOGNIYPkM__Ki5XmgsNwM1F0kX2PKqAL-wXo4T_fdgWq9SQVP2f-ZilzWQ0tfCyMuGw
            client-name: Gravity-SDOH-EHR-App
            provider: ehr-provider
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            # scope 'launch/patient' for a standalone launch if needed.
            scope: 'patient/*.*,user/*.read,openid,fhirUser,launch,launch/patient'
        provider:
          ehr-provider:
            token-uri: https://auth.logicahealth.org/token
            # We need to explicitly set the 'aud' query param to enable standalone launch.
            authorization-uri: https://auth.logicahealth.org/authorize?aud=${ehr.fhir-server-uri}
            user-info-uri: https://auth.logicahealth.org/userinfo
            jwk-set-uri: https://auth.logicahealth.org/jwk
            userNameAttribute: sub
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB

swagger:
  title: SDOH Exchange EHR App API
  contact:
    name: Gravity Project
    url: https://www.hl7.org/gravity/
scheduling:
  task-polling-delay-millis: 10000